-- -----------------------------------------------------
-- Table `Fits_Repo`
-- -----------------------------------------------------
 CREATE TABLE "FITS"."FRT_FITS_REPOPLDG_INST"
   (	"F_FORM_ID" NUMBER(10,0),
	"F_FORM_NUM" VARCHAR2(30 BYTE),
	"APRVFORM_NUM" VARCHAR2(30 BYTE),
	"F_TRDACCT" VARCHAR2(30 BYTE),
	"F_PORTFACCT_SECU" VARCHAR2(30 BYTE),
	"F_PORTFACCT_CASH" VARCHAR2(30 BYTE),
	"F_CUSTACCT_SECU" VARCHAR2(30 BYTE),
	"F_CUSTACCT_CASH" VARCHAR2(30 BYTE),
	"F_REPO_CODE" VARCHAR2(30 BYTE),
	"F_INSTRUMENT" VARCHAR2(30 BYTE),
	"F_EXECUTION" VARCHAR2(30 BYTE),
	"F_SETTLE_TYPE1ST" VARCHAR2(30 BYTE),
	"F_SETTLE_TYPE2ND" VARCHAR2(30 BYTE),
	"F_COUNT" NUMBER(10,0),
	"F_REPO_RATE" NUMBER(10,6),
	"F_AMOUNT" NUMBER(38,6),
	"F_MATURE_AMOUNT" NUMBER(38,6),
	"F_BEG_DATE" VARCHAR2(20 BYTE),
	"F_END_DATE" VARCHAR2(20 BYTE),
	"F_SUBMIT_DATE" VARCHAR2(20 BYTE),
	"F_INITIATOR" VARCHAR2(30 BYTE),
	"F_EXECUTOR" VARCHAR2(30 BYTE),
	"F_TRADE_DIRECTION" VARCHAR2(10 BYTE),
	"F_ACCOUNTING_TYPE" VARCHAR2(10 BYTE),
	"F_COUNTERPARTY_ID" VARCHAR2(10 BYTE),
	"F_CP_TRADER" VARCHAR2(30 BYTE),
	"F_CP_CASHACC" VARCHAR2(30 BYTE),
	"F_TRADE_DATE" VARCHAR2(20 BYTE),
	"F_SETTLE_DATE1ST" VARCHAR2(20 BYTE),
	"F_SETTLE_DATE2ND" VARCHAR2(20 BYTE),
	"F_SETTLE_SPEED" VARCHAR2(10 BYTE),
	"F_QUOTE_TYPE" VARCHAR2(10 BYTE),
	"F_AMOUNT_BALANCE" NUMBER(38,6),
	"F_INST_STATUS" VARCHAR2(10 BYTE),
	"F_REMARKS" VARCHAR2(200 BYTE),
	"F_TRD_AI" NUMBER(31,16),
	"F_TRD_FULL_PRICE" NUMBER(31,16),
	"F_TRD_PAR_VALUE" NUMBER(38,6),
	"F_TRD_NET_PRICE" NUMBER(31,16),
	"F_TRD_YTM" NUMBER(31,16),
	"F_TRD_TOTOL_AI" NUMBER(31,16),
	"F_TRD_SETTLE_AMOUNT" NUMBER(31,16),
	"F_PLEDGE_RATIO" NUMBER(10,6),
	"F_PLEDGE_TERM" NUMBER(4,0),
	"F_TRD_BONDPRICE_TYPE" VARCHAR2(10 BYTE),
	"AUDIT_CREATEDBY" VARCHAR2(64 BYTE),
	"AUDIT_CREATETIME" VARCHAR2(30 BYTE),
	"AUDIT_MODIFIEDBY" VARCHAR2(64 BYTE),
	"AUDIT_MODIFIEDTIME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITSTS" ;

   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_FORM_ID" IS '	记录ID	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_FORM_NUM" IS '	指令单编号	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."APRVFORM_NUM" IS '	对应审批单编号	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRDACCT" IS '	交易账户	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_PORTFACCT_SECU" IS '	组合证券账户	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_PORTFACCT_CASH" IS '	组合资金账户	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_CUSTACCT_SECU" IS '	托管证券账户	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_CUSTACCT_CASH" IS '	托管资金账户	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_REPO_CODE" IS '	标的回购代码	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_INSTRUMENT" IS '	质押债券代码	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_EXECUTION" IS '	执行市场	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_SETTLE_TYPE1ST" IS '	首次结算方式	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_SETTLE_TYPE2ND" IS '	到期结算方式	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_COUNT" IS '	投资指令回购数量	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_REPO_RATE" IS '	回购利率	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_AMOUNT" IS '	投资指令回购面额	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_MATURE_AMOUNT" IS '	投资指令到期还款面额	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_BEG_DATE" IS '	投资指令有效开始日期	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_END_DATE" IS '	投资指令有效结束日期	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_SUBMIT_DATE" IS '	投资指令提交日期	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_INITIATOR" IS '	指令发起人	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_EXECUTOR" IS '	指令执行人	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRADE_DIRECTION" IS '	交易方向	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_ACCOUNTING_TYPE" IS '	会计分类	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_COUNTERPARTY_ID" IS '	交易对手	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_CP_TRADER" IS '	对手交易员	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_CP_CASHACC" IS '	对手资金账号	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRADE_DATE" IS '	交易日期	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_SETTLE_DATE1ST" IS '	首次结算日期	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_SETTLE_DATE2ND" IS '	到期结算日期	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_SETTLE_SPEED" IS '	清算速度	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_QUOTE_TYPE" IS '	报价方式	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_AMOUNT_BALANCE" IS '	指令单资金余额	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_INST_STATUS" IS '	指令状态	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_REMARKS" IS '	备注	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_AI" IS '	标的债券的单位应计利息	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_FULL_PRICE" IS '	标的债券的全价	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_PAR_VALUE" IS '	标的债券的券面金额	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_NET_PRICE" IS '	标的债券的净价	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_YTM" IS '	标的债券的到期收益率	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_TOTOL_AI" IS '	总应计利息	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_SETTLE_AMOUNT" IS '	结算金额	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_PLEDGE_RATIO" IS '	质押债券的折扣率	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_PLEDGE_TERM" IS '	回购期限(天）	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."F_TRD_BONDPRICE_TYPE" IS '	标的债券的净价或全价	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."AUDIT_CREATEDBY" IS '	留痕字段-创建人	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."AUDIT_CREATETIME" IS '	留痕字段-创建时间	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."AUDIT_MODIFIEDBY" IS '	留痕字段-修改人	';
   COMMENT ON COLUMN "FITS"."FRT_FITS_REPOPLDG_INST"."AUDIT_MODIFIEDTIME" IS '	留痕字段-修改时间	';
   COMMENT ON TABLE "FITS"."FRT_FITS_REPOPLDG_INST"  IS '银行间质押式回购投资指令表';
--------------------------------------------------------
--  DDL for Index FRT_FITS_REPOPLDG_INST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FITS"."FRT_FITS_REPOPLDG_INST_PK" ON "FITS"."FRT_FITS_REPOPLDG_INST" ("F_FORM_NUM")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITSTS" ;
--------------------------------------------------------
--  Constraints for Table FRT_FITS_REPOPLDG_INST
--------------------------------------------------------

  ALTER TABLE "FITS"."FRT_FITS_REPOPLDG_INST" ADD CONSTRAINT "FRT_FITS_REPOPLDG_INST_PK" PRIMARY KEY ("F_FORM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITSTS"  ENABLE;
  ALTER TABLE "FITS"."FRT_FITS_REPOPLDG_INST" MODIFY ("F_FORM_NUM" NOT NULL ENABLE);
  ALTER TABLE "FITS"."FRT_FITS_REPOPLDG_INST" MODIFY ("F_FORM_ID" NOT NULL ENABLE);
